// Taller — UI strings (EN / FR / ES). Keep keys in sync across languages.

export const STRINGS = {
  en: {
    appName: 'Taller',
    tagline: 'Your service manuals. Searchable. Offline.',

    nav: { home: 'Home', equipment: 'Equipment', library: 'Manuals', ask: 'Ask', more: 'More' },

    time: { today: 'today', inDays: 'in {n} days', daysAgo: '{n} days ago' },

    home: {
      noEquipmentTitle: 'No machines registered yet',
      noEquipmentText: 'Your manuals are ready. Add the machines you look after to see what is down and what maintenance is due.',
      title: 'Workshop', subtitle: 'Your equipment at a glance',
      welcomeTitle: 'Welcome to your workshop', welcomeText: 'Add the equipment you look after and the service manuals you use. Everything stays on this phone.',
      addEquipment: 'Add equipment', addManual: 'Add a manual', tryDemo: 'Try the demo',
      tileEquipment: 'Equipment', tileUptime: 'Uptime', tileDown: 'Out of service', tilePmDue: 'PM due',
      partsNeeded: '{n} spare part needed — see request|{n} spare parts needed — see request', needsAttention: 'Needs attention', allGood: 'All equipment operational — nothing due.',
      quickActions: 'Quick actions', recent: 'Recent activity',
    },

    equipment: {
      moreFields: 'More details',
      fewerFields: 'Fewer details',
      title: 'Equipment', add: 'Add equipment', save: 'Save equipment', saved: 'Equipment saved', needName: 'Give the equipment a name.',
      saveAdd: 'Save & add another',
      emptyTitle: 'No equipment yet', emptyText: 'Register the machines you maintain — one card each, with status, maintenance schedule, manual and history.',
      searchPh: 'Search equipment, model, serial, location…', noneMatch: 'No equipment matches.', filterAll: 'All',
      name: 'Name', namePh: 'e.g. Suction pump — Ward 3', type: 'Type',
      manufacturer: 'Manufacturer', model: 'Model', serial: 'Serial number', serialPh: 'Serial no.',
      assetTag: 'Asset / tag no.', location: 'Location', locationPh: 'e.g. Maternity', power: 'Power',
      statusLabel: 'Status', riskLabel: 'Risk', riskAuto: 'Risk level: {r} (by type)', acquired: 'Acquired / installed',
      notes: 'Notes', notesPh: 'Anything useful for the next repair…', addPhoto: 'Add photo (nameplate, fault)',
      manual: 'Service manual', attachManual: 'Link a manual', noManualsYet: 'Add a manual first, then link it here.',
      openManual: 'Open manual', ask: 'Ask the manual', specs: 'Details', setStatus: 'Set status', statusSet: 'Status: {s}',
      partsNeeded: 'Spare parts needed', noParts: 'No parts flagged. Add any part you are waiting for.', partPh: 'e.g. Diaphragm kit PK-110',
      history: 'Service history', delete: 'Delete equipment', deleteConfirm: 'Delete "{name}" and its history from this device?',
      qty: 'Qty', printRecord: 'Print record',
      downDays: 'Down {n}d', downSince: 'Out of service for {n} day (since {d})|Out of service for {n} days (since {d})', downToday: 'Out of service since today',
      types: {
        oxygen_concentrator: 'Oxygen concentrator', ventilator: 'Ventilator', anaesthesia: 'Anaesthesia machine',
        patient_monitor: 'Patient monitor', defibrillator: 'Defibrillator', infant_incubator: 'Infant incubator',
        infant_warmer: 'Infant warmer', cpap: 'CPAP machine', infusion_pump: 'Infusion pump', syringe_pump: 'Syringe pump',
        electrosurgical: 'Electrosurgical unit', suction_pump: 'Suction pump', phototherapy: 'Phototherapy unit',
        ecg: 'ECG machine', ultrasound: 'Ultrasound scanner', xray: 'X-ray unit', autoclave: 'Autoclave / sterilizer',
        vaccine_fridge: 'Vaccine refrigerator', pulse_oximeter: 'Pulse oximeter', nebulizer: 'Nebulizer',
        centrifuge: 'Centrifuge', microscope: 'Microscope', bp_monitor: 'Blood pressure monitor',
        fetal_doppler: 'Fetal doppler', exam_light: 'Examination light', weighing_scale: 'Weighing scale',
        glucometer: 'Glucometer', dental_unit: 'Dental unit', other: 'Other equipment',
      },
      status: { working: 'Working', down: 'Out of service', awaiting_parts: 'Awaiting parts', retired: 'Retired' },
      risk: { high: 'High risk', medium: 'Medium risk', low: 'Low risk' },
    },

    pm: {
      unknownShort: 'No record',
      unknown: 'No service recorded yet',
      title: 'Preventive maintenance', none: 'No schedule set.', noneShort: 'None',
      every: 'Every', everyDays: 'Every {n} days', lastDone: 'Last done', markDone: 'Mark PM done',
      doneToast: 'Preventive maintenance recorded.', autoNote: 'Preventive maintenance completed.',
      due: 'PM due', soon: 'PM soon', overdueBy: 'Overdue by {n} day|Overdue by {n} days', dueToday: 'Due today',
      dueIn: 'Due in {n} day|Due in {n} days', nextOn: 'Next: {d}',
      remind: 'Add PM reminder',
    },

    reports: {
      title: 'Reports', empty: 'Add equipment to generate reports and a spare-parts request.',
      total: 'Total', outOfService: 'Out of service', partsLines: 'Parts lines',
      partsRequest: 'Spare parts request', noParts: 'No spare parts flagged. Add them on each machine.',
      print: 'Print / PDF', pmTitle: 'Maintenance due', pmNone: 'Nothing due or overdue.',
      inventory: 'Inventory', inventoryText: '{n} machine in the register.|{n} machines in the register.', statusReport: 'Equipment status report',
      fleetSummary: 'Fleet status summary', partsSub: 'Spare parts required, by machine.', part: 'Part needed',
      generated: 'Generated {d}', downloaded: 'File downloaded',
      downTitle: 'Out of service', addToCalendar: 'Add PM to phone calendar', pmEventTitle: 'PM due: {name}',
    },

    qr: {
      libFailed: 'Couldn\'t load the QR generator — connect to the internet once, then try again.',
      unavailable: 'QR unavailable offline',
      building: 'Preparing labels… {n}/{total}',
      title: 'Asset tag (QR)',
      explain: 'Print this code, stick it on the machine, and scan it to open this record instantly.',
      printLabel: 'Print label', printAll: 'Print asset labels', labelsTitle: 'Asset labels', noneToLabel: 'No equipment to label yet.',
    },
    scan: {
      title: 'Scan asset tag', scan: 'Scan',
      hint: 'Point the camera at a Taller QR label.',
      orType: 'Or type the tag / serial number:', typePh: 'Asset tag or serial',
      notFound: 'No machine found for “{q}”.', noCamera: 'Camera not available — type the code below.',
      unsupported: 'Scanning needs Chrome. Type the code below instead.',
      addNew: 'Add as new equipment',
    },
    backup: {
      skippedNewer: '{n} machine was newer on this phone and was kept.|{n} machines were newer on this phone and were kept.',
      cancelled: 'Backup cancelled — nothing was saved.',
      failed: 'The backup could not be created. Nothing was saved.',
      unknownDate: 'unknown date',
      confirmIntro: 'This backup was made on {d}. Restoring it will:',
      confirmAdd: 'add {n} new machine|add {n} new machines',
      confirmUpdate: 'overwrite {n} machine you already have|overwrite {n} machines you already have',
      confirmOlder: 'skip {n} machine that is newer on this phone|skip {n} machines that are newer on this phone',
      confirmLogs: 'merge {n} service record (duplicates are skipped)|merge {n} service records (duplicates are skipped)',
      confirmGo: 'Restore',
      title: 'Backup & restore',
      intro: 'Your equipment, photos and history live only on this phone. Back them up so you never lose your work — and to move to a new phone. Save the file somewhere safe, or send it to yourself on WhatsApp / email.',
      now: 'Back up now', share: 'Send backup to myself', done: 'Backup saved',
      lastAt: 'Last backup: {d}', never: 'Not backed up yet.',
      restoreTitle: 'Restore', restoreText: 'Restore from a backup file (merges into what you have).',
      restoreBtn: 'Choose backup file', restored: 'Restored {n} machine.|Restored {n} machines.',
      reimport: 'Re-import your {n} manual — it stays as your own PDF file.|Re-import your {n} manuals — they stay as your own PDF files.',
      badFile: 'That file is not a valid Taller backup.',
      tooNew: 'This backup is from a newer version of Taller.',
      manualsNote: 'Manuals (your PDF files) are not in the backup — re-import them after restoring.',
      remindTitle: 'Protect your data', remindText: 'Back up your equipment & history — it only lives on this phone.',
    },

    common: {
      confirm: 'Confirm',
      dismiss: 'Dismiss',
      storageFull: 'Phone storage is full — free up some space and try again.',
      cancel: 'Cancel', save: 'Save', delete: 'Delete', close: 'Close',
      back: 'Back', ok: 'OK', share: 'Share', copy: 'Copy', copied: 'Copied!',
      loading: 'Loading…', error: 'Something went wrong', retry: 'Retry',
      yes: 'Yes', no: 'No', optional: 'optional', search: 'Search',
      open: 'Open', add: 'Add', done: 'Done', stop: 'Stop', edit: 'Edit',
      confirmDelete: 'Delete this? This cannot be undone.',
    },

    onboarding: {
      more: 'What it does',
      welcome: 'Welcome to Taller',
      p1t: 'Every manual in your pocket',
      p1s: 'Import the PDF service manuals you already have. They stay on your phone.',
      p2t: 'Find the fix in seconds',
      p2s: 'Search faults, error codes or parts — offline — and jump to the exact page.',
      p3t: 'Free forever',
      p3s: 'Open source. No accounts, no ads, no tracking.',
      chooseLang: 'Language',
      start: 'Add my first manual',
      tryDemo: 'Try the demo manual',
      restore: 'Restore from a backup',
    },

    brand: {
      scanTitle: 'Open it on your phone',
      scanText: 'Scan with your camera — Taller installs from the browser and then works fully offline.',
      foot: 'Free & open source (Apache-2.0) · No accounts · Your files never leave your device',
      shareText: 'Taller — free & open-source app for biomedical technicians: your manuals, offline, plus equipment maintenance.',
    },

    library: {
      saving: 'Saving to this phone…',
      importCancelled: 'Import cancelled — nothing was saved.',
      storageFull: 'Your phone is full, so the manual was not saved. Free some space (photos, videos or another manual) and try again.',
      engineOffline: 'The app needs internet once to finish setting up. Connect, then add the manual again — this PDF is fine.',
      title: 'Manuals',
      searchAll: 'Search all manuals… (fault, error code, part)',
      addManual: 'Add manual (PDF)',
      emptyTitle: 'No manuals yet',
      emptyText: 'Add the PDF service manuals you already have on your phone. They never leave your device.',
      demoBtn: 'Try with a demo manual',
      importing: 'Importing…',
      readingFile: 'Reading file…',
      extracting: 'Reading page {x} of {y}…',
      indexing: 'Building search index…',
      imported: 'Manual added: {name}',
      importFailed: 'Could not import this PDF. The file may be damaged or protected.',
      scannedBadge: 'Scanned — text search off',
      scannedHint: 'This manual is a scan (photos of pages). You can still open and read it. Use OCR to make it searchable.',
      makeSearchable: 'Make searchable (OCR)',
      pages: '{n} page|{n} pages',
      deleteManual: 'Delete manual',
      deleteConfirm: 'Delete "{name}" from this device?',
      storage: 'Storage used: {used}',
      bigFileWarn: 'This file is {mb} MB. Import may be slow on this phone. Continue?',
      betaTitle: 'This is a beta — help decide its future',
      betaText: 'Real technicians are validating whether this app is worth building properly. Your opinion decides.',
      betaCta: '60-second feedback',
      installApp: 'Install app',
      installed: 'App installed — it now works fully offline.',
      keepOpen: 'Keep the app open while importing.',
      suggestTitle: 'Try a search',
      shareApp: 'Share Taller with a colleague',
      linkCopied: 'Link copied — paste it anywhere',
      rename: 'Rename',
      renamed: 'Renamed',
      onlyPdf: 'Only PDF files can be imported.', demoOffline: 'The demo needs internet the first time.',
    },

    find: {
      title: 'Find a manual',
      intro: 'Search these free public libraries for a service manual, then import the PDF here.',
      forDevice: 'What are you looking for?',
      queryPlaceholder: 'Make and model, e.g. Philips SP-100',
      note: 'These are independent, third-party libraries — Taller does not host manuals. Check that the manual matches your exact model. Once downloaded, use “Add manual (PDF)” to import it.',
      offline: 'You are offline — connect to the internet to open these libraries.',
      cta: 'Find a manual online',
      open: 'Open {name}',
      srcIfixit: '13,000+ free biomedical repair manuals',
      srcFranks: 'Free service manuals and guides for low-resource hospitals',
      srcMedwrench: 'Community equipment library and forums',
      srcWebName: 'Web search',
      srcWeb: 'Search the whole web for a PDF',
    },

    search: {
      resultsFor: 'Results for “{q}”',
      noResults: 'No matches in your manuals.',
      tips: 'Try: the error code (e.g. “E4”), the fault (“no suction”), or a part name.',
      page: 'p. {n}',
    },

    reader: {
      pageOf: '{p} / {n}',
      findInManual: 'Search inside this manual…',
      copyPageText: 'Copy page text',
      prevPage: 'Previous page', nextPage: 'Next page', zoomIn: 'Zoom in', zoomOut: 'Zoom out',
      copiedPage: 'Page text copied',
      noTextPage: 'No text on this page (scanned image).',
      resultCtx: 'Match on this page:',
    },

    ask: {
      extractBadge: 'Exact pages from your manuals',
      weakBadge: 'Weak match',
      weakText: 'Nothing in your manuals matches this question well. The pages below are the closest, but they may be about something else — read them before trusting anything.',
      insufficientBadge: 'Not in your manuals',
      truncated: 'This answer was cut off before the end. Open the cited pages — steps may be missing.',
      badCitation: 'Warning: page {p} was cited but was not among the pages searched. Do not trust that citation.',
      partialPages: 'Only part of each page was read. A procedure may continue beyond what the assistant saw — check the full page.',
      relevance: 'Relevance',
      conf: { weak: 'weak', fair: 'fair', good: 'good' },
      title: 'Ask your manuals',
      hint: 'Describe the fault. The answer comes ONLY from the manuals you added, with the page cited.',
      placeholder: 'e.g. Suction pump shows E3 and stops after a few seconds',
      allManuals: 'All manuals',
      askBtn: 'Ask',
      thinking: 'Answering from your manuals…',
      answer: 'Answer',
      aiBadge: 'AI · grounded in your manuals',
      offlineBadge: 'Offline · exact excerpts from your manuals',
      sources: 'Sources',
      bestPages: 'Best matching pages',
      openPage: 'Open p. {n}',
      copyPrompt: 'Copy prompt for ChatGPT / other AI',
      promptCopied: 'Prompt copied. Paste it into ChatGPT, Claude, Gemini…',
      aiError: 'AI service not reachable — showing the matching manual pages instead.',
      noMatches: 'Nothing about this was found in your manuals.',
      noMatchesTips: 'Try other words: the exact error code, the part name, or the symptom. Or check that the right manual is imported.',
      safety: 'Answers come only from your manuals — always verify on the cited page before acting. Follow electrical safety procedures. Never bypass safety interlocks or alarms.',
      needManuals: 'Add at least one manual first — the assistant only answers from YOUR manuals.',
      goAdd: 'Add a manual',
      suggestTitle: 'Try asking',
    },

    logbook: {
      showMore: 'Show {n} more',
      title: 'Service history',
      newEntry: 'New entry',
      logFault: 'Log a fault',
      setMachine: 'Set machine to:', date: 'Date',
      equipment: 'Equipment',
      equipmentPh: 'e.g. Suction pump — Ward 3',
      noEquip: 'No equipment', otherEquip: 'Other / not in register',
      type: 'Type',
      typeRepair: 'Repair', typePM: 'Preventive', typeInspection: 'Inspection',
      problem: 'Problem / work done',
      problemPh: 'e.g. E3 error — cleaned filter, replaced tubing',
      status: 'Status',
      statusFixed: 'Fixed', statusPending: 'Pending', statusPart: 'Needs part',
      minutes: 'Minutes spent',
      addPhoto: 'Add photo',
      saveEntry: 'Save entry',
      saved: 'Entry saved',
      empty: 'No entries yet. A log helps you justify your work and plan preventive maintenance.',
      emptyEquip: 'No history yet for this machine.',
      export: 'Export CSV',
      exported: 'CSV exported',
      entries: '{n} entry|{n} entries',
    },

    feedback: {
      title: '60-second feedback',
      intro: 'This beta exists to answer one question: would Taller help real technicians? Your honest answer — including “no” — decides whether it gets built properly.',
      q1: 'Finding the right manual or page — how often is it a problem in your work?',
      q1a: 'Every week', q1b: 'Sometimes', q1c: 'Rarely',
      q2: 'Internet at your workshop:',
      q2a: 'None / very bad', q2b: 'Comes and goes', q2c: 'Stable and affordable',
      q3: 'Do you already use ChatGPT or similar AI with your PDFs for repairs?',
      q3a: 'Yes, works well for me', q3b: 'Tried it — didn’t really help', q3c: 'Never tried',
      q4: 'A fault log that takes under 1 minute per entry — would you use it?',
      q4a: 'Yes', q4b: 'Maybe', q4c: 'No',
      q5: 'How many of your manuals are scanned photocopies?',
      q5a: 'Most of them', q5b: 'Some', q5c: 'Almost none',
      comments: 'Would this app help you in real work? What is missing?',
      commentsPh: 'Be brutal — honest answers are worth more than kind ones.',
      country: 'Country + role',
      countryPh: 'e.g. Kenya, hospital BMET',
      includeStats: 'Include my usage stats (manuals added, searches made — nothing else)',
      sendEmail: 'Send by email',
      sendShare: 'Send via WhatsApp / other app',
      copyAll: 'Copy my answers (paste in forum / WhatsApp)',
      thanks: 'Thank you! Your feedback decides what happens next.',
      answerFirst: 'Please answer at least one question first.',
    },

    ocr: {
      needInternet: 'OCR needs internet once to download its engine (~7 MB). Connect to the internet, then try again.',
      engineReady: 'The OCR engine is already on this phone — this works offline.',
      savedAsYouGo: 'Pages are saved as they are read — you can stop any time and continue later.',
      storageFull: 'Your phone is full. The pages read so far are saved; free some space to finish.',
      title: 'Make manual searchable',
      intro: 'This manual is scanned (photos of pages). OCR reads the text so you can search it. It runs on your phone: about 10–40 seconds per page. Keep the app open, ideally plugged in.',
      firstTime: 'The first time needs internet once (to load the OCR engine, ~7 MB). After that it works offline.',
      lang: 'Manual language',
      start: 'Start OCR',
      progress: 'Reading page {x} of {y}…',
      done: 'Done — {n} pages are now searchable.',
      stopped: 'Stopped. {n} pages processed so far are searchable.',
      failed: 'OCR could not run on this device.',
    },

    more: {
      offlinePartial: 'Partly ready for offline use. Stay connected a moment longer to finish downloading.',
      offlineFailed: 'Could not finish setting up for offline use. Reopen the app while connected.',
      title: 'More',
      language: 'Language',
      theme: 'Theme', themeAuto: 'Auto', themeLight: 'Light', themeDark: 'Dark',
      feedbackCta: 'Give 60-second feedback',
      aiTitle: 'AI assistant (online)',
      aiOn: 'Connected — grounded answers when you have internet.',
      aiOff: 'Not configured. The app works offline: search + exact excerpts + copy-prompt. An optional free AI server can be enabled by the project.',
      aiUrl: 'AI server URL',
      storageTitle: 'Storage',
      persistOn: 'Protected storage: your manuals won’t be auto-deleted.',
      persistOff: 'Storage not yet protected — install the app to protect it.',
      aboutTitle: 'About Taller',
      aboutText: 'Free and open source, forever. No ads, no accounts, no tracking. Your manuals and logs never leave your phone (if you enable the online AI, only the excerpts needed to answer are sent, and nothing is stored). Built for biomedical technicians everywhere.',
      disclaimer: 'Taller is an information tool for professionals. It is not a substitute for manufacturer documentation, training or local regulations. Always verify cited pages and follow safety procedures.',
      source: 'Source code',
      license: 'License: Apache-2.0',
      reset: 'Delete ALL app data',
      resetConfirm: 'Delete all manuals, logs and settings from this device?',
      version: 'Version',
      openInChrome: 'To install and use offline, open this page in Chrome (menu ⋮ → Open in Chrome).',
      updateReady: 'Update ready — close and reopen the app to apply.',
      reload: 'Reload',
      offlineReady: 'Ready — Taller now works without internet.',
    },
  },

  fr: {
    appName: 'Taller',
    tagline: 'Vos manuels de service. Consultables. Hors ligne.',

    nav: { home: 'Accueil', equipment: 'Équipements', library: 'Manuels', ask: 'Assistant', more: 'Plus' },

    time: { today: "aujourd'hui", inDays: 'dans {n} jours', daysAgo: 'il y a {n} jours' },

    home: {
      noEquipmentTitle: 'Aucun équipement enregistré',
      noEquipmentText: 'Vos manuels sont prêts. Ajoutez les équipements dont vous vous occupez pour voir ce qui est en panne et ce qui est à entretenir.',
      title: 'Atelier', subtitle: "Vos équipements en un coup d'œil",
      welcomeTitle: 'Bienvenue dans votre atelier', welcomeText: 'Ajoutez les équipements dont vous vous occupez et les manuels que vous utilisez. Tout reste sur ce téléphone.',
      addEquipment: 'Ajouter un équipement', addManual: 'Ajouter un manuel', tryDemo: 'Essayer la démo',
      tileEquipment: 'Équipements', tileUptime: 'Disponibilité', tileDown: 'Hors service', tilePmDue: 'MP à faire',
      partsNeeded: '{n} pièce détachée nécessaire — voir la demande|{n} pièces détachées nécessaires — voir la demande', needsAttention: 'À traiter', allGood: 'Tous les équipements fonctionnent — rien à faire.',
      quickActions: 'Actions rapides', recent: 'Activité récente',
    },

    equipment: {
      moreFields: 'Plus de détails',
      fewerFields: 'Moins de détails',
      title: 'Équipements', add: 'Ajouter un équipement', save: 'Enregistrer', saved: 'Équipement enregistré', needName: "Donnez un nom à l'équipement.",
      saveAdd: 'Enregistrer et ajouter',
      emptyTitle: 'Aucun équipement', emptyText: 'Enregistrez les machines que vous entretenez — une fiche chacune, avec statut, échéance de maintenance, manuel et historique.',
      searchPh: 'Chercher équipement, modèle, série, lieu…', noneMatch: 'Aucun équipement ne correspond.', filterAll: 'Tous',
      name: 'Nom', namePh: 'ex. Aspirateur — Salle 3', type: 'Type',
      manufacturer: 'Fabricant', model: 'Modèle', serial: 'Numéro de série', serialPh: 'N° de série',
      assetTag: "N° d'inventaire", location: 'Emplacement', locationPh: 'ex. Maternité', power: 'Alimentation',
      statusLabel: 'Statut', riskLabel: 'Risque', riskAuto: 'Niveau de risque : {r} (selon le type)', acquired: 'Acquis / installé',
      notes: 'Notes', notesPh: 'Tout ce qui sera utile pour la prochaine réparation…', addPhoto: 'Ajouter une photo (plaque, panne)',
      manual: 'Manuel de service', attachManual: 'Associer un manuel', noManualsYet: "Ajoutez d'abord un manuel, puis associez-le ici.",
      openManual: 'Ouvrir le manuel', ask: 'Consulter le manuel', specs: 'Détails', setStatus: 'Définir le statut', statusSet: 'Statut : {s}',
      partsNeeded: 'Pièces détachées nécessaires', noParts: 'Aucune pièce signalée. Ajoutez toute pièce attendue.', partPh: 'ex. Kit membranes PK-110',
      history: 'Historique de service', delete: "Supprimer l'équipement", deleteConfirm: 'Supprimer « {name} » et son historique de cet appareil ?',
      qty: 'Qté', printRecord: 'Imprimer la fiche',
      downDays: 'Arrêt {n}j', downSince: 'Hors service depuis {n} jour (depuis {d})|Hors service depuis {n} jours (depuis {d})', downToday: "Hors service depuis aujourd'hui",
      types: {
        oxygen_concentrator: "Concentrateur d'oxygène", ventilator: 'Ventilateur', anaesthesia: "Machine d'anesthésie",
        patient_monitor: 'Moniteur patient', defibrillator: 'Défibrillateur', infant_incubator: 'Incubateur néonatal',
        infant_warmer: 'Table chauffante', cpap: 'Appareil CPAP', infusion_pump: 'Pompe à perfusion', syringe_pump: 'Pousse-seringue',
        electrosurgical: 'Bistouri électrique', suction_pump: 'Aspirateur de mucosités', phototherapy: 'Unité de photothérapie',
        ecg: 'Électrocardiographe', ultrasound: 'Échographe', xray: 'Appareil de radiographie', autoclave: 'Autoclave / stérilisateur',
        vaccine_fridge: 'Réfrigérateur à vaccins', pulse_oximeter: 'Oxymètre de pouls', nebulizer: 'Nébuliseur',
        centrifuge: 'Centrifugeuse', microscope: 'Microscope', bp_monitor: 'Tensiomètre',
        fetal_doppler: 'Doppler fœtal', exam_light: "Lampe d'examen", weighing_scale: 'Balance',
        glucometer: 'Glucomètre', dental_unit: 'Unit dentaire', other: 'Autre équipement',
      },
      status: { working: 'En service', down: 'Hors service', awaiting_parts: 'En attente de pièces', retired: 'Réformé' },
      risk: { high: 'Risque élevé', medium: 'Risque moyen', low: 'Risque faible' },
    },

    pm: {
      unknownShort: 'Aucun suivi',
      unknown: 'Aucun entretien enregistré',
      title: 'Maintenance préventive', none: 'Aucune échéance définie.', noneShort: 'Aucune',
      every: 'Tous les', everyDays: 'Tous les {n} jours', lastDone: 'Dernière fois', markDone: 'Marquer MP faite',
      doneToast: 'Maintenance préventive enregistrée.', autoNote: 'Maintenance préventive effectuée.',
      due: 'MP à faire', soon: 'MP bientôt', overdueBy: 'En retard de {n} jour|En retard de {n} jours', dueToday: "À faire aujourd'hui",
      dueIn: 'À faire dans {n} jour|À faire dans {n} jours', nextOn: 'Prochaine : {d}',
      remind: 'Ajouter un rappel de MP',
    },

    reports: {
      title: 'Rapports', empty: 'Ajoutez des équipements pour générer des rapports et une demande de pièces.',
      total: 'Total', outOfService: 'Hors service', partsLines: 'Lignes de pièces',
      partsRequest: 'Demande de pièces détachées', noParts: 'Aucune pièce signalée. Ajoutez-les sur chaque machine.',
      print: 'Imprimer / PDF', pmTitle: 'Maintenance à faire', pmNone: 'Rien à faire ni en retard.',
      inventory: 'Inventaire', inventoryText: '{n} machine au registre.|{n} machines au registre.', statusReport: "Rapport d'état des équipements",
      fleetSummary: "Résumé de l'état du parc", partsSub: 'Pièces détachées requises, par machine.', part: 'Pièce requise',
      generated: 'Généré le {d}', downloaded: 'Fichier téléchargé',
      downTitle: 'Hors service', addToCalendar: 'Ajouter la MP au calendrier', pmEventTitle: 'MP à faire : {name}',
    },

    qr: {
      libFailed: 'Impossible de charger le générateur de QR — connectez-vous à internet une fois, puis réessayez.',
      unavailable: 'QR indisponible hors ligne',
      building: 'Préparation des étiquettes… {n}/{total}',
      title: 'Étiquette (QR)',
      explain: 'Imprimez ce code, collez-le sur la machine, et scannez-le pour ouvrir sa fiche instantanément.',
      printLabel: "Imprimer l'étiquette", printAll: 'Imprimer les étiquettes', labelsTitle: "Étiquettes d'équipement", noneToLabel: 'Aucun équipement à étiqueter.',
    },
    scan: {
      title: 'Scanner une étiquette', scan: 'Scanner',
      hint: 'Dirigez la caméra vers une étiquette QR Taller.',
      orType: "Ou saisissez l'étiquette / le n° de série :", typePh: "N° d'inventaire ou de série",
      notFound: 'Aucune machine trouvée pour « {q} ».', noCamera: 'Caméra indisponible — saisissez le code ci-dessous.',
      unsupported: 'Le scan nécessite Chrome. Saisissez le code ci-dessous.',
      addNew: 'Ajouter comme nouvel équipement',
    },
    backup: {
      skippedNewer: '{n} équipement était plus récent sur ce téléphone et a été conservé.|{n} équipements étaient plus récents sur ce téléphone et ont été conservés.',
      cancelled: 'Sauvegarde annulée — rien n\'a été enregistré.',
      failed: 'La sauvegarde n\'a pas pu être créée. Rien n\'a été enregistré.',
      unknownDate: 'date inconnue',
      confirmIntro: 'Cette sauvegarde date du {d}. La restaurer va :',
      confirmAdd: 'ajouter {n} nouvel équipement|ajouter {n} nouveaux équipements',
      confirmUpdate: 'remplacer {n} équipement déjà présent|remplacer {n} équipements déjà présents',
      confirmOlder: 'ignorer {n} équipement plus récent sur ce téléphone|ignorer {n} équipements plus récents sur ce téléphone',
      confirmLogs: 'fusionner {n} intervention (les doublons sont ignorés)|fusionner {n} interventions (les doublons sont ignorés)',
      confirmGo: 'Restaurer',
      title: 'Sauvegarde & restauration',
      intro: "Vos équipements, photos et historique n'existent que sur ce téléphone. Sauvegardez-les pour ne rien perdre — et pour changer de téléphone. Enregistrez le fichier en lieu sûr, ou envoyez-le-vous par WhatsApp / e-mail.",
      now: 'Sauvegarder maintenant', share: "M'envoyer la sauvegarde", done: 'Sauvegarde enregistrée',
      lastAt: 'Dernière sauvegarde : {d}', never: 'Pas encore sauvegardé.',
      restoreTitle: 'Restaurer', restoreText: "Restaurer depuis un fichier de sauvegarde (fusionne avec l'existant).",
      restoreBtn: 'Choisir le fichier', restored: '{n} équipement restauré.|{n} équipements restaurés.',
      reimport: 'Réimportez votre {n} manuel — il reste votre propre fichier PDF.|Réimportez vos {n} manuels — ils restent vos propres fichiers PDF.',
      badFile: "Ce fichier n'est pas une sauvegarde Taller valide.",
      tooNew: "Cette sauvegarde provient d'une version plus récente de Taller.",
      manualsNote: 'Les manuels (vos fichiers PDF) ne sont pas inclus — réimportez-les après restauration.',
      remindTitle: 'Protégez vos données', remindText: "Sauvegardez vos équipements et l'historique — tout est seulement sur ce téléphone.",
    },

    common: {
      confirm: 'Confirmation',
      dismiss: 'Masquer',
      storageFull: 'Le stockage du téléphone est plein — libérez de l\'espace et réessayez.',
      cancel: 'Annuler', save: 'Enregistrer', delete: 'Supprimer', close: 'Fermer',
      back: 'Retour', ok: 'OK', share: 'Partager', copy: 'Copier', copied: 'Copié !',
      loading: 'Chargement…', error: 'Une erreur est survenue', retry: 'Réessayer',
      yes: 'Oui', no: 'Non', optional: 'facultatif', search: 'Rechercher',
      open: 'Ouvrir', add: 'Ajouter', done: 'Terminé', stop: 'Arrêter', edit: 'Modifier',
      confirmDelete: 'Supprimer ? Cette action est définitive.',
    },

    onboarding: {
      more: 'Ce que ça fait',
      welcome: 'Bienvenue sur Taller',
      p1t: 'Tous vos manuels en poche',
      p1s: 'Importez les manuels de service PDF que vous avez déjà. Ils restent sur votre téléphone.',
      p2t: 'La panne trouvée en secondes',
      p2s: 'Cherchez pannes, codes erreur ou pièces — hors ligne — et ouvrez la page exacte.',
      p3t: 'Gratuit pour toujours',
      p3s: 'Open source. Sans compte, sans pub, sans traçage.',
      chooseLang: 'Langue',
      start: 'Ajouter mon premier manuel',
      tryDemo: 'Essayer le manuel de démo',
      restore: 'Restaurer depuis une sauvegarde',
    },

    brand: {
      scanTitle: 'Ouvrez-la sur votre téléphone',
      scanText: 'Scannez avec l’appareil photo — Taller s’installe depuis le navigateur puis fonctionne entièrement hors ligne.',
      foot: 'Gratuit et open source (Apache-2.0) · Sans compte · Vos fichiers ne quittent jamais votre appareil',
      shareText: 'Taller — appli gratuite et open source pour techniciens biomédicaux : vos manuels, hors ligne, et la maintenance des équipements.',
    },

    library: {
      saving: 'Enregistrement sur le téléphone…',
      importCancelled: 'Import annulé — rien n\'a été enregistré.',
      storageFull: 'Le téléphone est plein : le manuel n\'a pas été enregistré. Libérez de l\'espace (photos, vidéos ou un autre manuel) puis réessayez.',
      engineOffline: 'L\'appli a besoin d\'internet une seule fois pour terminer son installation. Connectez-vous, puis rajoutez le manuel — ce PDF n\'a rien.',
      title: 'Manuels',
      searchAll: 'Chercher dans tous les manuels… (panne, code erreur)',
      addManual: 'Ajouter un manuel (PDF)',
      emptyTitle: 'Aucun manuel pour l’instant',
      emptyText: 'Ajoutez les manuels de service PDF que vous avez déjà sur votre téléphone. Ils ne quittent jamais votre appareil.',
      demoBtn: 'Essayer avec un manuel de démo',
      importing: 'Importation…',
      readingFile: 'Lecture du fichier…',
      extracting: 'Lecture de la page {x} sur {y}…',
      indexing: 'Création de l’index de recherche…',
      imported: 'Manuel ajouté : {name}',
      importFailed: 'Impossible d’importer ce PDF. Fichier endommagé ou protégé.',
      scannedBadge: 'Scanné — recherche texte désactivée',
      scannedHint: 'Ce manuel est un scan (photos de pages). Vous pouvez le lire. Utilisez l’OCR pour le rendre consultable.',
      makeSearchable: 'Rendre consultable (OCR)',
      pages: '{n} page|{n} pages',
      deleteManual: 'Supprimer le manuel',
      deleteConfirm: 'Supprimer « {name} » de cet appareil ?',
      storage: 'Stockage utilisé : {used}',
      bigFileWarn: 'Ce fichier fait {mb} Mo. L’import peut être lent sur ce téléphone. Continuer ?',
      betaTitle: 'Ceci est une bêta — aidez à décider de son avenir',
      betaText: 'Des techniciens réels valident si cette appli mérite d’être développée sérieusement. Votre avis décide.',
      betaCta: 'Avis en 60 secondes',
      installApp: 'Installer l’appli',
      installed: 'Appli installée — elle fonctionne maintenant 100 % hors ligne.',
      keepOpen: 'Gardez l’appli ouverte pendant l’importation.',
      suggestTitle: 'Essayez une recherche',
      shareApp: 'Partager Taller avec un collègue',
      linkCopied: 'Lien copié — collez-le où vous voulez',
      rename: 'Renommer',
      renamed: 'Renommé',
      onlyPdf: 'Seuls les fichiers PDF peuvent être importés.', demoOffline: 'La démo nécessite internet la première fois.',
    },

    find: {
      title: 'Trouver un manuel',
      intro: 'Cherchez un manuel de service dans ces bibliothèques publiques gratuites, puis importez le PDF ici.',
      forDevice: 'Que cherchez-vous ?',
      queryPlaceholder: 'Marque et modèle, ex. Philips SP-100',
      note: 'Ce sont des bibliothèques tierces indépendantes — Taller n’héberge aucun manuel. Vérifiez que le manuel correspond à votre modèle exact. Une fois téléchargé, utilisez « Ajouter un manuel (PDF) » pour l’importer.',
      offline: 'Vous êtes hors ligne — connectez-vous à internet pour ouvrir ces bibliothèques.',
      cta: 'Trouver un manuel en ligne',
      open: 'Ouvrir {name}',
      srcIfixit: '13 000+ manuels de réparation biomédicale gratuits',
      srcFranks: 'Manuels de service et guides gratuits pour hôpitaux à faibles ressources',
      srcMedwrench: 'Bibliothèque d’équipements et forums communautaires',
      srcWebName: 'Recherche web',
      srcWeb: 'Chercher un PDF sur tout le web',
    },

    search: {
      resultsFor: 'Résultats pour « {q} »',
      noResults: 'Aucun résultat dans vos manuels.',
      tips: 'Essayez : le code erreur (ex. « E4 »), la panne (« pas d’aspiration ») ou le nom d’une pièce.',
      page: 'p. {n}',
    },

    reader: {
      pageOf: '{p} / {n}',
      findInManual: 'Chercher dans ce manuel…',
      copyPageText: 'Copier le texte de la page',
      prevPage: 'Page précédente', nextPage: 'Page suivante', zoomIn: 'Zoom avant', zoomOut: 'Zoom arrière',
      copiedPage: 'Texte de la page copié',
      noTextPage: 'Pas de texte sur cette page (image scannée).',
      resultCtx: 'Correspondance sur cette page :',
    },

    ask: {
      extractBadge: 'Pages exactes de vos manuels',
      weakBadge: 'Correspondance faible',
      weakText: 'Rien dans vos manuels ne correspond vraiment à cette question. Les pages ci-dessous sont les plus proches, mais elles peuvent parler d\'autre chose — lisez-les avant de vous y fier.',
      insufficientBadge: 'Absent de vos manuels',
      truncated: 'Cette réponse a été coupée avant la fin. Ouvrez les pages citées — des étapes peuvent manquer.',
      badCitation: 'Attention : la page {p} est citée mais ne fait pas partie des pages consultées. Ne vous fiez pas à cette citation.',
      partialPages: 'Seule une partie de chaque page a été lue. Une procédure peut se poursuivre au-delà — vérifiez la page entière.',
      relevance: 'Pertinence',
      conf: { weak: 'faible', fair: 'moyenne', good: 'bonne' },
      title: 'Interrogez vos manuels',
      hint: 'Décrivez la panne. La réponse vient UNIQUEMENT des manuels ajoutés, avec la page citée.',
      placeholder: 'ex. L’aspirateur de mucosités affiche E3 puis s’arrête',
      allManuals: 'Tous les manuels',
      askBtn: 'Demander',
      thinking: 'Réponse à partir de vos manuels…',
      answer: 'Réponse',
      aiBadge: 'IA · ancrée dans vos manuels',
      offlineBadge: 'Hors ligne · extraits exacts de vos manuels',
      sources: 'Sources',
      bestPages: 'Meilleures pages correspondantes',
      openPage: 'Ouvrir p. {n}',
      copyPrompt: 'Copier le prompt pour ChatGPT / autre IA',
      promptCopied: 'Prompt copié. Collez-le dans ChatGPT, Claude, Gemini…',
      aiError: 'Service IA injoignable — voici les pages correspondantes du manuel.',
      noMatches: 'Rien trouvé à ce sujet dans vos manuels.',
      noMatchesTips: 'Essayez d’autres mots : le code erreur exact, le nom de la pièce, le symptôme. Vérifiez que le bon manuel est importé.',
      safety: 'Les réponses viennent uniquement de vos manuels — vérifiez toujours la page citée avant d’agir. Respectez les procédures de sécurité électrique. Ne contournez jamais les sécurités ni les alarmes.',
      needManuals: 'Ajoutez d’abord au moins un manuel — l’assistant ne répond qu’à partir de VOS manuels.',
      goAdd: 'Ajouter un manuel',
      suggestTitle: 'Essayez de demander',
    },

    logbook: {
      showMore: 'Afficher {n} de plus',
      title: 'Historique de service',
      newEntry: 'Nouvelle entrée',
      logFault: 'Signaler une panne',
      setMachine: 'Mettre la machine sur :', date: 'Date',
      equipment: 'Équipement',
      equipmentPh: 'ex. Aspirateur — Salle 3',
      noEquip: 'Aucun équipement', otherEquip: 'Autre / hors registre',
      type: 'Type',
      typeRepair: 'Réparation', typePM: 'Préventive', typeInspection: 'Inspection',
      problem: 'Problème / travail effectué',
      problemPh: 'ex. Erreur E3 — filtre nettoyé, tuyau remplacé',
      status: 'Statut',
      statusFixed: 'Réparé', statusPending: 'En attente', statusPart: 'Pièce requise',
      minutes: 'Minutes passées',
      addPhoto: 'Ajouter une photo',
      saveEntry: 'Enregistrer',
      saved: 'Entrée enregistrée',
      empty: 'Aucune entrée. Un journal aide à justifier votre travail et à planifier la maintenance préventive.',
      emptyEquip: 'Aucun historique pour cette machine.',
      export: 'Exporter CSV',
      exported: 'CSV exporté',
      entries: '{n} entrée|{n} entrées',
    },

    feedback: {
      title: 'Votre avis en 60 secondes',
      intro: 'Cette bêta existe pour répondre à une question : Taller aiderait-il les techniciens réels ? Votre réponse honnête — même « non » — décide si l’appli sera développée sérieusement.',
      q1: 'Trouver le bon manuel ou la bonne page — à quelle fréquence est-ce un problème dans votre travail ?',
      q1a: 'Chaque semaine', q1b: 'Parfois', q1c: 'Rarement',
      q2: 'Internet dans votre atelier :',
      q2a: 'Aucun / très mauvais', q2b: 'Intermittent', q2c: 'Stable et abordable',
      q3: 'Utilisez-vous déjà ChatGPT (ou autre IA) avec vos PDF pour les réparations ?',
      q3a: 'Oui, ça marche bien', q3b: 'Essayé — pas vraiment utile', q3c: 'Jamais essayé',
      q4: 'Un journal de pannes en moins d’1 minute par entrée — l’utiliseriez-vous ?',
      q4a: 'Oui', q4b: 'Peut-être', q4c: 'Non',
      q5: 'Quelle part de vos manuels sont des photocopies scannées ?',
      q5a: 'La plupart', q5b: 'Certains', q5c: 'Presque aucun',
      comments: 'Cette appli vous aiderait-elle vraiment ? Que manque-t-il ?',
      commentsPh: 'Soyez direct — les réponses honnêtes valent plus que les gentilles.',
      country: 'Pays + fonction',
      countryPh: 'ex. Sénégal, technicien biomédical hospitalier',
      includeStats: 'Inclure mes statistiques d’usage (manuels ajoutés, recherches — rien d’autre)',
      sendEmail: 'Envoyer par e-mail',
      sendShare: 'Envoyer via WhatsApp / autre appli',
      copyAll: 'Copier mes réponses (à coller sur le forum / WhatsApp)',
      thanks: 'Merci ! Votre avis décide de la suite.',
      answerFirst: 'Répondez d’abord à au moins une question.',
    },

    ocr: {
      needInternet: 'L\'OCR a besoin d\'internet une seule fois pour télécharger son moteur (~7 Mo). Connectez-vous, puis réessayez.',
      engineReady: 'Le moteur OCR est déjà sur le téléphone — tout fonctionne hors ligne.',
      savedAsYouGo: 'Les pages sont enregistrées au fur et à mesure — vous pouvez arrêter et reprendre plus tard.',
      storageFull: 'Le téléphone est plein. Les pages déjà lues sont enregistrées ; libérez de l\'espace pour terminer.',
      title: 'Rendre le manuel consultable',
      intro: 'Ce manuel est scanné (photos de pages). L’OCR lit le texte pour permettre la recherche. Tout se passe sur votre téléphone : environ 10 à 40 secondes par page. Gardez l’appli ouverte, idéalement en charge.',
      firstTime: 'La première fois nécessite internet une seule fois (moteur OCR, ~7 Mo). Ensuite, tout fonctionne hors ligne.',
      lang: 'Langue du manuel',
      start: 'Lancer l’OCR',
      progress: 'Lecture de la page {x} sur {y}…',
      done: 'Terminé — {n} pages sont maintenant consultables.',
      stopped: 'Arrêté. Les {n} pages traitées sont consultables.',
      failed: 'L’OCR n’a pas pu fonctionner sur cet appareil.',
    },

    more: {
      offlinePartial: 'Partiellement prêt pour le hors ligne. Restez connecté un instant pour terminer le téléchargement.',
      offlineFailed: 'Impossible de terminer l\'installation hors ligne. Rouvrez l\'appli en étant connecté.',
      title: 'Plus',
      language: 'Langue',
      theme: 'Thème', themeAuto: 'Auto', themeLight: 'Clair', themeDark: 'Sombre',
      feedbackCta: 'Donner votre avis (60 s)',
      aiTitle: 'Assistant IA (en ligne)',
      aiOn: 'Connecté — réponses ancrées quand vous avez internet.',
      aiOff: 'Non configuré. L’appli fonctionne hors ligne : recherche + extraits exacts + copie de prompt. Un serveur IA gratuit optionnel peut être activé par le projet.',
      aiUrl: 'URL du serveur IA',
      storageTitle: 'Stockage',
      persistOn: 'Stockage protégé : vos manuels ne seront pas supprimés automatiquement.',
      persistOff: 'Stockage pas encore protégé — installez l’appli pour le protéger.',
      aboutTitle: 'À propos de Taller',
      aboutText: 'Gratuit et open source, pour toujours. Sans publicité, sans compte, sans traçage. Vos manuels et journaux ne quittent jamais votre téléphone (si l’IA en ligne est activée, seuls les extraits nécessaires à la réponse sont envoyés, et rien n’est conservé). Conçu pour les techniciens biomédicaux du monde entier.',
      disclaimer: 'Taller est un outil d’information pour professionnels. Il ne remplace ni la documentation du fabricant, ni la formation, ni la réglementation locale. Vérifiez toujours les pages citées et respectez les procédures de sécurité.',
      source: 'Code source',
      license: 'Licence : Apache-2.0',
      reset: 'Supprimer TOUTES les données',
      resetConfirm: 'Supprimer tous les manuels, journaux et réglages de cet appareil ?',
      version: 'Version',
      openInChrome: 'Pour installer et utiliser hors ligne, ouvrez cette page dans Chrome (menu ⋮ → Ouvrir dans Chrome).',
      updateReady: 'Mise à jour prête — fermez et rouvrez l’appli pour l’appliquer.',
      reload: 'Recharger',
      offlineReady: 'Prêt — Taller fonctionne maintenant sans internet.',
    },
  },

  es: {
    appName: 'Taller',
    tagline: 'Tus manuales de servicio. Buscables. Sin internet.',

    nav: { home: 'Inicio', equipment: 'Equipos', library: 'Manuales', ask: 'Asistente', more: 'Más' },

    time: { today: 'hoy', inDays: 'en {n} días', daysAgo: 'hace {n} días' },

    home: {
      noEquipmentTitle: 'Aún no hay equipos registrados',
      noEquipmentText: 'Tus manuales están listos. Añade los equipos que mantienes para ver qué está parado y qué mantenimiento toca.',
      title: 'Taller', subtitle: 'Tus equipos de un vistazo',
      welcomeTitle: 'Bienvenido a tu taller', welcomeText: 'Añade los equipos que mantienes y los manuales que usas. Todo se queda en este teléfono.',
      addEquipment: 'Añadir equipo', addManual: 'Añadir un manual', tryDemo: 'Probar la demo',
      tileEquipment: 'Equipos', tileUptime: 'Disponibilidad', tileDown: 'Fuera de servicio', tilePmDue: 'MP pendiente',
      partsNeeded: '{n} repuesto necesario — ver solicitud|{n} repuestos necesarios — ver solicitud', needsAttention: 'Requiere atención', allGood: 'Todos los equipos operativos — nada pendiente.',
      quickActions: 'Acciones rápidas', recent: 'Actividad reciente',
    },

    equipment: {
      moreFields: 'Más detalles',
      fewerFields: 'Menos detalles',
      title: 'Equipos', add: 'Añadir equipo', save: 'Guardar equipo', saved: 'Equipo guardado', needName: 'Ponle un nombre al equipo.',
      saveAdd: 'Guardar y añadir otro',
      emptyTitle: 'Aún no hay equipos', emptyText: 'Registra las máquinas que mantienes — una ficha cada una, con estado, plan de mantenimiento, manual e historial.',
      searchPh: 'Buscar equipo, modelo, serie, ubicación…', noneMatch: 'Ningún equipo coincide.', filterAll: 'Todos',
      name: 'Nombre', namePh: 'ej. Aspirador — Sala 3', type: 'Tipo',
      manufacturer: 'Fabricante', model: 'Modelo', serial: 'Número de serie', serialPh: 'N.º de serie',
      assetTag: 'N.º de inventario', location: 'Ubicación', locationPh: 'ej. Maternidad', power: 'Alimentación',
      statusLabel: 'Estado', riskLabel: 'Riesgo', riskAuto: 'Nivel de riesgo: {r} (según el tipo)', acquired: 'Adquirido / instalado',
      notes: 'Notas', notesPh: 'Lo que sea útil para la próxima reparación…', addPhoto: 'Añadir foto (placa, avería)',
      manual: 'Manual de servicio', attachManual: 'Asociar un manual', noManualsYet: 'Añade primero un manual y luego asócialo aquí.',
      openManual: 'Abrir manual', ask: 'Consultar el manual', specs: 'Detalles', setStatus: 'Cambiar estado', statusSet: 'Estado: {s}',
      partsNeeded: 'Repuestos necesarios', noParts: 'Sin repuestos marcados. Añade cualquier pieza que esperes.', partPh: 'ej. Kit de membranas PK-110',
      history: 'Historial de servicio', delete: 'Eliminar equipo', deleteConfirm: '¿Eliminar «{name}» y su historial de este dispositivo?',
      qty: 'Cant.', printRecord: 'Imprimir ficha',
      downDays: 'Parado {n}d', downSince: 'Fuera de servicio hace {n} día (desde {d})|Fuera de servicio hace {n} días (desde {d})', downToday: 'Fuera de servicio desde hoy',
      types: {
        oxygen_concentrator: 'Concentrador de oxígeno', ventilator: 'Ventilador', anaesthesia: 'Máquina de anestesia',
        patient_monitor: 'Monitor de paciente', defibrillator: 'Desfibrilador', infant_incubator: 'Incubadora neonatal',
        infant_warmer: 'Cuna de calor radiante', cpap: 'Equipo CPAP', infusion_pump: 'Bomba de infusión', syringe_pump: 'Bomba de jeringa',
        electrosurgical: 'Bisturí eléctrico', suction_pump: 'Aspirador de secreciones', phototherapy: 'Unidad de fototerapia',
        ecg: 'Electrocardiógrafo', ultrasound: 'Ecógrafo', xray: 'Equipo de rayos X', autoclave: 'Autoclave / esterilizador',
        vaccine_fridge: 'Refrigerador de vacunas', pulse_oximeter: 'Pulsioxímetro', nebulizer: 'Nebulizador',
        centrifuge: 'Centrífuga', microscope: 'Microscopio', bp_monitor: 'Tensiómetro',
        fetal_doppler: 'Doppler fetal', exam_light: 'Lámpara de exploración', weighing_scale: 'Báscula',
        glucometer: 'Glucómetro', dental_unit: 'Unidad dental', other: 'Otro equipo',
      },
      status: { working: 'Operativo', down: 'Fuera de servicio', awaiting_parts: 'Esperando repuestos', retired: 'Retirado' },
      risk: { high: 'Riesgo alto', medium: 'Riesgo medio', low: 'Riesgo bajo' },
    },

    pm: {
      unknownShort: 'Sin registro',
      unknown: 'Sin mantenimiento registrado',
      title: 'Mantenimiento preventivo', none: 'Sin plan definido.', noneShort: 'Ninguno',
      every: 'Cada', everyDays: 'Cada {n} días', lastDone: 'Última vez', markDone: 'Marcar MP hecho',
      doneToast: 'Mantenimiento preventivo registrado.', autoNote: 'Mantenimiento preventivo realizado.',
      due: 'MP pendiente', soon: 'MP pronto', overdueBy: 'Vencido hace {n} día|Vencido hace {n} días', dueToday: 'Vence hoy',
      dueIn: 'Vence en {n} día|Vence en {n} días', nextOn: 'Próximo: {d}',
      remind: 'Añadir recordatorio de MP',
    },

    reports: {
      title: 'Informes', empty: 'Añade equipos para generar informes y una solicitud de repuestos.',
      total: 'Total', outOfService: 'Fuera de servicio', partsLines: 'Líneas de repuestos',
      partsRequest: 'Solicitud de repuestos', noParts: 'Sin repuestos marcados. Añádelos en cada máquina.',
      print: 'Imprimir / PDF', pmTitle: 'Mantenimiento pendiente', pmNone: 'Nada pendiente ni vencido.',
      inventory: 'Inventario', inventoryText: '{n} máquina en el registro.|{n} máquinas en el registro.', statusReport: 'Informe de estado de equipos',
      fleetSummary: 'Resumen del estado del parque', partsSub: 'Repuestos requeridos, por máquina.', part: 'Pieza necesaria',
      generated: 'Generado el {d}', downloaded: 'Archivo descargado',
      downTitle: 'Fuera de servicio', addToCalendar: 'Añadir MP al calendario', pmEventTitle: 'MP pendiente: {name}',
    },

    qr: {
      libFailed: 'No se pudo cargar el generador de QR — conéctate a internet una vez y vuelve a intentarlo.',
      unavailable: 'QR no disponible sin conexión',
      building: 'Preparando etiquetas… {n}/{total}',
      title: 'Etiqueta (QR)',
      explain: 'Imprime este código, pégalo en la máquina y escanéalo para abrir su ficha al instante.',
      printLabel: 'Imprimir etiqueta', printAll: 'Imprimir etiquetas', labelsTitle: 'Etiquetas de equipos', noneToLabel: 'No hay equipos que etiquetar.',
    },
    scan: {
      title: 'Escanear etiqueta', scan: 'Escanear',
      hint: 'Apunta la cámara a una etiqueta QR de Taller.',
      orType: 'O escribe la etiqueta / n.º de serie:', typePh: 'N.º de inventario o serie',
      notFound: 'No se encontró ninguna máquina para «{q}».', noCamera: 'Cámara no disponible — escribe el código abajo.',
      unsupported: 'Escanear necesita Chrome. Escribe el código abajo.',
      addNew: 'Añadir como equipo nuevo',
    },
    backup: {
      skippedNewer: '{n} equipo era más reciente en este teléfono y se conservó.|{n} equipos eran más recientes en este teléfono y se conservaron.',
      cancelled: 'Copia cancelada: no se guardó nada.',
      failed: 'No se pudo crear la copia de seguridad. No se guardó nada.',
      unknownDate: 'fecha desconocida',
      confirmIntro: 'Esta copia es del {d}. Al restaurarla:',
      confirmAdd: 'añadir {n} equipo nuevo|añadir {n} equipos nuevos',
      confirmUpdate: 'sobrescribir {n} equipo que ya tienes|sobrescribir {n} equipos que ya tienes',
      confirmOlder: 'omitir {n} equipo más reciente en este teléfono|omitir {n} equipos más recientes en este teléfono',
      confirmLogs: 'fusionar {n} registro de servicio (se omiten duplicados)|fusionar {n} registros de servicio (se omiten duplicados)',
      confirmGo: 'Restaurar',
      title: 'Copia de seguridad',
      intro: 'Tus equipos, fotos e historial solo existen en este teléfono. Haz una copia para no perder tu trabajo — y para cambiar de teléfono. Guarda el archivo en lugar seguro, o envíatelo por WhatsApp / correo.',
      now: 'Hacer copia ahora', share: 'Enviarme la copia', done: 'Copia guardada',
      lastAt: 'Última copia: {d}', never: 'Sin copia todavía.',
      restoreTitle: 'Restaurar', restoreText: 'Restaura desde un archivo de copia (se fusiona con lo que tienes).',
      restoreBtn: 'Elegir archivo', restored: '{n} equipo restaurado.|{n} equipos restaurados.',
      reimport: 'Vuelve a importar tu {n} manual — se guarda como tu propio PDF.|Vuelve a importar tus {n} manuales — se guardan como tus propios PDF.',
      badFile: 'Ese archivo no es una copia válida de Taller.',
      tooNew: 'Esta copia es de una versión más nueva de Taller.',
      manualsNote: 'Los manuales (tus PDF) no se incluyen en la copia — reimpórtalos tras restaurar.',
      remindTitle: 'Protege tus datos', remindText: 'Haz copia de tus equipos e historial — solo están en este teléfono.',
    },

    common: {
      confirm: 'Confirmar',
      dismiss: 'Descartar',
      storageFull: 'El almacenamiento del teléfono está lleno — libera espacio y vuelve a intentarlo.',
      cancel: 'Cancelar', save: 'Guardar', delete: 'Eliminar', close: 'Cerrar',
      back: 'Atrás', ok: 'OK', share: 'Compartir', copy: 'Copiar', copied: '¡Copiado!',
      loading: 'Cargando…', error: 'Algo salió mal', retry: 'Reintentar',
      yes: 'Sí', no: 'No', optional: 'opcional', search: 'Buscar',
      open: 'Abrir', add: 'Añadir', done: 'Hecho', stop: 'Parar', edit: 'Editar',
      confirmDelete: '¿Eliminar? No se puede deshacer.',
    },

    onboarding: {
      more: 'Qué hace',
      welcome: 'Bienvenido a Taller',
      p1t: 'Todos tus manuales en el bolsillo',
      p1s: 'Importa los manuales de servicio PDF que ya tienes. Se quedan en tu teléfono.',
      p2t: 'Encuentra la solución en segundos',
      p2s: 'Busca averías, códigos de error o piezas — sin internet — y salta a la página exacta.',
      p3t: 'Gratis para siempre',
      p3s: 'Open source. Sin cuentas, sin anuncios, sin rastreo.',
      chooseLang: 'Idioma',
      start: 'Añadir mi primer manual',
      tryDemo: 'Probar el manual de demo',
      restore: 'Restaurar desde una copia',
    },

    brand: {
      scanTitle: 'Ábrela en tu teléfono',
      scanText: 'Escanea con la cámara — Taller se instala desde el navegador y después funciona totalmente sin internet.',
      foot: 'Gratis y open source (Apache-2.0) · Sin cuentas · Tus archivos nunca salen de tu dispositivo',
      shareText: 'Taller — app gratis y open source para técnicos biomédicos: tus manuales, sin internet, y el mantenimiento de equipos.',
    },

    library: {
      saving: 'Guardando en el teléfono…',
      importCancelled: 'Importación cancelada: no se guardó nada.',
      storageFull: 'Tu teléfono está lleno, así que el manual no se guardó. Libera espacio (fotos, vídeos u otro manual) e inténtalo de nuevo.',
      engineOffline: 'La app necesita internet una sola vez para terminar de instalarse. Conéctate y añade el manual otra vez: este PDF está bien.',
      title: 'Manuales',
      searchAll: 'Buscar en todos los manuales… (avería, código de error)',
      addManual: 'Añadir manual (PDF)',
      emptyTitle: 'Aún no hay manuales',
      emptyText: 'Añade los manuales de servicio PDF que ya tienes en tu teléfono. Nunca salen de tu dispositivo.',
      demoBtn: 'Probar con un manual de demo',
      importing: 'Importando…',
      readingFile: 'Leyendo archivo…',
      extracting: 'Leyendo página {x} de {y}…',
      indexing: 'Creando índice de búsqueda…',
      imported: 'Manual añadido: {name}',
      importFailed: 'No se pudo importar este PDF. Puede estar dañado o protegido.',
      scannedBadge: 'Escaneado — búsqueda de texto desactivada',
      scannedHint: 'Este manual es un escaneo (fotos de páginas). Puedes leerlo igualmente. Usa OCR para hacerlo buscable.',
      makeSearchable: 'Hacer buscable (OCR)',
      pages: '{n} página|{n} páginas',
      deleteManual: 'Eliminar manual',
      deleteConfirm: '¿Eliminar «{name}» de este dispositivo?',
      storage: 'Almacenamiento usado: {used}',
      bigFileWarn: 'Este archivo pesa {mb} MB. La importación puede ser lenta en este teléfono. ¿Continuar?',
      betaTitle: 'Esto es una beta — ayuda a decidir su futuro',
      betaText: 'Técnicos reales están validando si esta app merece construirse en serio. Tu opinión decide.',
      betaCta: 'Feedback en 60 segundos',
      installApp: 'Instalar app',
      installed: 'App instalada — ya funciona 100 % sin internet.',
      keepOpen: 'Mantén la app abierta durante la importación.',
      suggestTitle: 'Prueba una búsqueda',
      shareApp: 'Comparte Taller con un colega',
      linkCopied: 'Enlace copiado — pégalo donde quieras',
      rename: 'Renombrar',
      renamed: 'Renombrado',
      onlyPdf: 'Solo se pueden importar archivos PDF.', demoOffline: 'La demo necesita internet la primera vez.',
    },

    find: {
      title: 'Buscar un manual',
      intro: 'Busca un manual de servicio en estas bibliotecas públicas gratuitas y luego importa el PDF aquí.',
      forDevice: '¿Qué estás buscando?',
      queryPlaceholder: 'Marca y modelo, p. ej. Philips SP-100',
      note: 'Son bibliotecas independientes de terceros — Taller no aloja ningún manual. Comprueba que el manual coincide con tu modelo exacto. Una vez descargado, usa «Añadir manual (PDF)» para importarlo.',
      offline: 'Estás sin conexión — conéctate a internet para abrir estas bibliotecas.',
      cta: 'Buscar un manual online',
      open: 'Abrir {name}',
      srcIfixit: '13.000+ manuales de reparación biomédica gratuitos',
      srcFranks: 'Manuales de servicio y guías gratis para hospitales con pocos recursos',
      srcMedwrench: 'Biblioteca de equipos y foros de la comunidad',
      srcWebName: 'Búsqueda web',
      srcWeb: 'Buscar un PDF en toda la web',
    },

    search: {
      resultsFor: 'Resultados para «{q}»',
      noResults: 'Sin coincidencias en tus manuales.',
      tips: 'Prueba: el código de error (ej. «E4»), la avería («no aspira») o el nombre de una pieza.',
      page: 'p. {n}',
    },

    reader: {
      pageOf: '{p} / {n}',
      findInManual: 'Buscar dentro de este manual…',
      copyPageText: 'Copiar texto de la página',
      prevPage: 'Página anterior', nextPage: 'Página siguiente', zoomIn: 'Acercar', zoomOut: 'Alejar',
      copiedPage: 'Texto copiado',
      noTextPage: 'Esta página no tiene texto (imagen escaneada).',
      resultCtx: 'Coincidencia en esta página:',
    },

    ask: {
      extractBadge: 'Páginas exactas de tus manuales',
      weakBadge: 'Coincidencia débil',
      weakText: 'Nada en tus manuales coincide bien con esta pregunta. Las páginas de abajo son las más cercanas, pero pueden tratar de otra cosa: léelas antes de fiarte.',
      insufficientBadge: 'No está en tus manuales',
      truncated: 'Esta respuesta se cortó antes del final. Abre las páginas citadas: pueden faltar pasos.',
      badCitation: 'Aviso: se cita la página {p}, pero no estaba entre las consultadas. No te fíes de esa cita.',
      partialPages: 'Solo se leyó parte de cada página. Un procedimiento puede continuar más allá: revisa la página completa.',
      relevance: 'Relevancia',
      conf: { weak: 'baja', fair: 'media', good: 'alta' },
      title: 'Pregunta a tus manuales',
      hint: 'Describe la avería. La respuesta sale SOLO de los manuales que añadiste, citando la página.',
      placeholder: 'ej. El aspirador marca E3 y se para a los pocos segundos',
      allManuals: 'Todos los manuales',
      askBtn: 'Preguntar',
      thinking: 'Respondiendo desde tus manuales…',
      answer: 'Respuesta',
      aiBadge: 'IA · anclada a tus manuales',
      offlineBadge: 'Sin internet · extractos exactos de tus manuales',
      sources: 'Fuentes',
      bestPages: 'Páginas que mejor coinciden',
      openPage: 'Abrir p. {n}',
      copyPrompt: 'Copiar prompt para ChatGPT / otra IA',
      promptCopied: 'Prompt copiado. Pégalo en ChatGPT, Claude, Gemini…',
      aiError: 'Servicio de IA no disponible — te muestro las páginas coincidentes del manual.',
      noMatches: 'No se encontró nada sobre esto en tus manuales.',
      noMatchesTips: 'Prueba otras palabras: el código de error exacto, el nombre de la pieza o el síntoma. Comprueba que el manual correcto está importado.',
      safety: 'Las respuestas salen solo de tus manuales — verifica siempre la página citada antes de actuar. Sigue los procedimientos de seguridad eléctrica. Nunca anules seguridades ni alarmas.',
      needManuals: 'Añade primero al menos un manual — el asistente solo responde desde TUS manuales.',
      goAdd: 'Añadir un manual',
      suggestTitle: 'Prueba a preguntar',
    },

    logbook: {
      showMore: 'Mostrar {n} más',
      title: 'Historial de servicio',
      newEntry: 'Nueva entrada',
      logFault: 'Registrar avería',
      setMachine: 'Poner la máquina en:', date: 'Fecha',
      equipment: 'Equipo',
      equipmentPh: 'ej. Aspirador — Sala 3',
      noEquip: 'Sin equipo', otherEquip: 'Otro / no registrado',
      type: 'Tipo',
      typeRepair: 'Reparación', typePM: 'Preventivo', typeInspection: 'Inspección',
      problem: 'Problema / trabajo realizado',
      problemPh: 'ej. Error E3 — filtro limpiado, tubo sustituido',
      status: 'Estado',
      statusFixed: 'Reparado', statusPending: 'Pendiente', statusPart: 'Falta pieza',
      minutes: 'Minutos empleados',
      addPhoto: 'Añadir foto',
      saveEntry: 'Guardar entrada',
      saved: 'Entrada guardada',
      empty: 'Sin entradas. Un registro ayuda a justificar tu trabajo y planificar el mantenimiento preventivo.',
      emptyEquip: 'Aún no hay historial para esta máquina.',
      export: 'Exportar CSV',
      exported: 'CSV exportado',
      entries: '{n} entrada|{n} entradas',
    },

    feedback: {
      title: 'Tu opinión en 60 segundos',
      intro: 'Esta beta existe para responder una pregunta: ¿ayudaría Taller a técnicos reales? Tu respuesta honesta — incluido un «no» — decide si se construye en serio.',
      q1: 'Encontrar el manual o la página correcta — ¿con qué frecuencia es un problema en tu trabajo?',
      q1a: 'Cada semana', q1b: 'A veces', q1c: 'Rara vez',
      q2: 'Internet en tu taller:',
      q2a: 'No hay / muy malo', q2b: 'Va y viene', q2c: 'Estable y barato',
      q3: '¿Ya usas ChatGPT u otra IA con tus PDF para reparaciones?',
      q3a: 'Sí, me funciona bien', q3b: 'Lo probé — no ayudó mucho', q3c: 'Nunca lo probé',
      q4: 'Un registro de averías de menos de 1 minuto por entrada — ¿lo usarías?',
      q4a: 'Sí', q4b: 'Quizás', q4c: 'No',
      q5: '¿Cuántos de tus manuales son fotocopias escaneadas?',
      q5a: 'La mayoría', q5b: 'Algunos', q5c: 'Casi ninguno',
      comments: '¿Te ayudaría esta app en el trabajo real? ¿Qué le falta?',
      commentsPh: 'Sé brutal — las respuestas honestas valen más que las amables.',
      country: 'País + puesto',
      countryPh: 'ej. Perú, técnico biomédico hospitalario',
      includeStats: 'Incluir mis estadísticas de uso (manuales añadidos, búsquedas — nada más)',
      sendEmail: 'Enviar por correo',
      sendShare: 'Enviar por WhatsApp / otra app',
      copyAll: 'Copiar mis respuestas (para pegar en foro / WhatsApp)',
      thanks: '¡Gracias! Tu opinión decide lo que pasa después.',
      answerFirst: 'Responde al menos una pregunta primero.',
    },

    ocr: {
      needInternet: 'El OCR necesita internet una sola vez para descargar su motor (~7 MB). Conéctate a internet e inténtalo de nuevo.',
      engineReady: 'El motor de OCR ya está en el teléfono: funciona sin conexión.',
      savedAsYouGo: 'Las páginas se guardan mientras se leen: puedes parar cuando quieras y continuar después.',
      storageFull: 'Tu teléfono está lleno. Las páginas ya leídas están guardadas; libera espacio para terminar.',
      title: 'Hacer buscable el manual',
      intro: 'Este manual está escaneado (fotos de páginas). El OCR lee el texto para poder buscarlo. Todo ocurre en tu teléfono: unos 10–40 segundos por página. Mantén la app abierta, mejor enchufado.',
      firstTime: 'La primera vez necesita internet una sola vez (motor OCR, ~7 MB). Después funciona sin conexión.',
      lang: 'Idioma del manual',
      start: 'Iniciar OCR',
      progress: 'Leyendo página {x} de {y}…',
      done: 'Listo — {n} páginas ya son buscables.',
      stopped: 'Parado. Las {n} páginas procesadas ya son buscables.',
      failed: 'El OCR no pudo funcionar en este dispositivo.',
    },

    more: {
      offlinePartial: 'Parcialmente listo para uso sin conexión. Sigue conectado un momento para terminar la descarga.',
      offlineFailed: 'No se pudo terminar la instalación para uso sin conexión. Vuelve a abrir la app con conexión.',
      title: 'Más',
      language: 'Idioma',
      theme: 'Tema', themeAuto: 'Auto', themeLight: 'Claro', themeDark: 'Oscuro',
      feedbackCta: 'Dar feedback (60 s)',
      aiTitle: 'Asistente IA (online)',
      aiOn: 'Conectado — respuestas ancladas cuando tengas internet.',
      aiOff: 'Sin configurar. La app funciona sin internet: búsqueda + extractos exactos + copiar prompt. El proyecto puede activar un servidor IA gratuito opcional.',
      aiUrl: 'URL del servidor IA',
      storageTitle: 'Almacenamiento',
      persistOn: 'Almacenamiento protegido: tus manuales no se borrarán automáticamente.',
      persistOff: 'Almacenamiento aún sin proteger — instala la app para protegerlo.',
      aboutTitle: 'Acerca de Taller',
      aboutText: 'Gratis y open source, para siempre. Sin anuncios, sin cuentas, sin rastreo. Tus manuales y registros nunca salen de tu teléfono (si activas la IA online, solo se envían los extractos necesarios para responder, y no se guarda nada). Hecho para técnicos biomédicos de todo el mundo.',
      disclaimer: 'Taller es una herramienta de información para profesionales. No sustituye la documentación del fabricante, la formación ni la normativa local. Verifica siempre las páginas citadas y sigue los procedimientos de seguridad.',
      source: 'Código fuente',
      license: 'Licencia: Apache-2.0',
      reset: 'Borrar TODOS los datos',
      resetConfirm: '¿Borrar todos los manuales, registros y ajustes de este dispositivo?',
      version: 'Versión',
      openInChrome: 'Para instalar y usar sin internet, abre esta página en Chrome (menú ⋮ → Abrir en Chrome).',
      updateReady: 'Actualización lista — cierra y vuelve a abrir la app.',
      reload: 'Recargar',
      offlineReady: 'Listo — Taller ya funciona sin internet.',
    },
  },

  pt: {
    appName: 'Taller',
    tagline: 'Os seus manuais de serviço. Pesquisáveis. Offline.',

    nav: { home: 'Início', equipment: 'Equipamentos', library: 'Manuais', ask: 'Assistente', more: 'Mais' },

    time: { today: 'hoje', inDays: 'em {n} dias', daysAgo: 'há {n} dias' },

    home: {
      noEquipmentTitle: 'Ainda não há equipamentos registados',
      noEquipmentText: 'Os seus manuais estão prontos. Adicione os equipamentos que mantém para ver o que está parado e que manutenção está pendente.',
      title: 'Oficina', subtitle: 'Os seus equipamentos num relance',
      welcomeTitle: 'Bem-vindo à sua oficina', welcomeText: 'Adicione os equipamentos que mantém e os manuais que usa. Tudo fica neste telemóvel.',
      addEquipment: 'Adicionar equipamento', addManual: 'Adicionar um manual', tryDemo: 'Experimentar a demo',
      tileEquipment: 'Equipamentos', tileUptime: 'Disponibilidade', tileDown: 'Fora de serviço', tilePmDue: 'MP a fazer',
      partsNeeded: '{n} peça necessária — ver pedido|{n} peças necessárias — ver pedido', needsAttention: 'Requer atenção', allGood: 'Todos os equipamentos operacionais — nada pendente.',
      quickActions: 'Ações rápidas', recent: 'Atividade recente',
    },

    equipment: {
      moreFields: 'Mais detalhes',
      fewerFields: 'Menos detalhes',
      title: 'Equipamentos', add: 'Adicionar equipamento', save: 'Guardar equipamento', saved: 'Equipamento guardado', needName: 'Dê um nome ao equipamento.',
      saveAdd: 'Guardar e adicionar outro',
      emptyTitle: 'Ainda sem equipamentos', emptyText: 'Registe as máquinas que mantém — uma ficha cada uma, com estado, plano de manutenção, manual e histórico.',
      searchPh: 'Procurar equipamento, modelo, série, localização…', noneMatch: 'Nenhum equipamento corresponde.', filterAll: 'Todos',
      name: 'Nome', namePh: 'ex. Aspirador — Enfermaria 3', type: 'Tipo',
      manufacturer: 'Fabricante', model: 'Modelo', serial: 'Número de série', serialPh: 'N.º de série',
      assetTag: 'N.º de inventário', location: 'Localização', locationPh: 'ex. Maternidade', power: 'Alimentação',
      statusLabel: 'Estado', riskLabel: 'Risco', riskAuto: 'Nível de risco: {r} (pelo tipo)', acquired: 'Adquirido / instalado',
      notes: 'Notas', notesPh: 'O que for útil para a próxima reparação…', addPhoto: 'Adicionar foto (placa, avaria)',
      manual: 'Manual de serviço', attachManual: 'Associar um manual', noManualsYet: 'Adicione primeiro um manual e depois associe-o aqui.',
      openManual: 'Abrir manual', ask: 'Consultar o manual', specs: 'Detalhes', setStatus: 'Definir estado', statusSet: 'Estado: {s}',
      partsNeeded: 'Peças necessárias', noParts: 'Sem peças assinaladas. Adicione qualquer peça em falta.', partPh: 'ex. Kit de membranas PK-110',
      history: 'Histórico de serviço', delete: 'Eliminar equipamento', deleteConfirm: 'Eliminar «{name}» e o seu histórico deste dispositivo?',
      qty: 'Qtd.', printRecord: 'Imprimir ficha',
      downDays: 'Parado {n}d', downSince: 'Fora de serviço há {n} dia (desde {d})|Fora de serviço há {n} dias (desde {d})', downToday: 'Fora de serviço desde hoje',
      types: {
        oxygen_concentrator: 'Concentrador de oxigénio', ventilator: 'Ventilador', anaesthesia: 'Máquina de anestesia',
        patient_monitor: 'Monitor de paciente', defibrillator: 'Desfibrilhador', infant_incubator: 'Incubadora neonatal',
        infant_warmer: 'Berço de calor radiante', cpap: 'Aparelho CPAP', infusion_pump: 'Bomba de perfusão', syringe_pump: 'Bomba de seringa',
        electrosurgical: 'Bisturi elétrico', suction_pump: 'Aspirador de secreções', phototherapy: 'Unidade de fototerapia',
        ecg: 'Eletrocardiógrafo', ultrasound: 'Ecógrafo', xray: 'Aparelho de raios X', autoclave: 'Autoclave / esterilizador',
        vaccine_fridge: 'Frigorífico de vacinas', pulse_oximeter: 'Oxímetro de pulso', nebulizer: 'Nebulizador',
        centrifuge: 'Centrifugadora', microscope: 'Microscópio', bp_monitor: 'Medidor de tensão',
        fetal_doppler: 'Doppler fetal', exam_light: 'Foco de exame', weighing_scale: 'Balança',
        glucometer: 'Glicómetro', dental_unit: 'Unidade dentária', other: 'Outro equipamento',
      },
      status: { working: 'Operacional', down: 'Fora de serviço', awaiting_parts: 'A aguardar peças', retired: 'Abatido' },
      risk: { high: 'Risco alto', medium: 'Risco médio', low: 'Risco baixo' },
    },

    pm: {
      unknownShort: 'Sem registo',
      unknown: 'Sem manutenção registada',
      title: 'Manutenção preventiva', none: 'Sem plano definido.', noneShort: 'Nenhum',
      every: 'A cada', everyDays: 'A cada {n} dias', lastDone: 'Última vez', markDone: 'Marcar MP feita',
      doneToast: 'Manutenção preventiva registada.', autoNote: 'Manutenção preventiva efetuada.',
      due: 'MP a fazer', soon: 'MP em breve', overdueBy: 'Atrasada {n} dia|Atrasada {n} dias', dueToday: 'A fazer hoje',
      dueIn: 'A fazer em {n} dia|A fazer em {n} dias', nextOn: 'Próxima: {d}',
      remind: 'Adicionar lembrete de MP',
    },

    reports: {
      title: 'Relatórios', empty: 'Adicione equipamentos para gerar relatórios e um pedido de peças.',
      total: 'Total', outOfService: 'Fora de serviço', partsLines: 'Linhas de peças',
      partsRequest: 'Pedido de peças', noParts: 'Sem peças assinaladas. Adicione-as em cada máquina.',
      print: 'Imprimir / PDF', pmTitle: 'Manutenção a fazer', pmNone: 'Nada a fazer nem atrasado.',
      inventory: 'Inventário', inventoryText: '{n} máquina no registo.|{n} máquinas no registo.', statusReport: 'Relatório de estado dos equipamentos',
      fleetSummary: 'Resumo do estado do parque', partsSub: 'Peças necessárias, por máquina.', part: 'Peça necessária',
      generated: 'Gerado em {d}', downloaded: 'Ficheiro transferido',
      downTitle: 'Fora de serviço', addToCalendar: 'Adicionar MP ao calendário', pmEventTitle: 'MP a fazer: {name}',
    },

    qr: {
      libFailed: 'Não foi possível carregar o gerador de QR — ligue-se à internet uma vez e tente novamente.',
      unavailable: 'QR indisponível offline',
      building: 'A preparar etiquetas… {n}/{total}',
      title: 'Etiqueta (QR)',
      explain: 'Imprima este código, cole-o na máquina e leia-o para abrir esta ficha de imediato.',
      printLabel: 'Imprimir etiqueta', printAll: 'Imprimir etiquetas', labelsTitle: 'Etiquetas de equipamento', noneToLabel: 'Sem equipamentos para etiquetar.',
    },
    scan: {
      title: 'Ler etiqueta', scan: 'Ler QR',
      hint: 'Aponte a câmara a uma etiqueta QR do Taller.',
      orType: 'Ou escreva a etiqueta / n.º de série:', typePh: 'N.º de inventário ou série',
      notFound: 'Nenhuma máquina encontrada para «{q}».', noCamera: 'Câmara indisponível — escreva o código abaixo.',
      unsupported: 'A leitura precisa do Chrome. Escreva o código abaixo.',
      addNew: 'Adicionar como novo equipamento',
    },
    backup: {
      skippedNewer: '{n} equipamento era mais recente neste telemóvel e foi mantido.|{n} equipamentos eram mais recentes neste telemóvel e foram mantidos.',
      cancelled: 'Cópia cancelada — nada foi guardado.',
      failed: 'Não foi possível criar a cópia de segurança. Nada foi guardado.',
      unknownDate: 'data desconhecida',
      confirmIntro: 'Esta cópia é de {d}. Ao restaurá-la:',
      confirmAdd: 'adicionar {n} equipamento novo|adicionar {n} equipamentos novos',
      confirmUpdate: 'substituir {n} equipamento que já tem|substituir {n} equipamentos que já tem',
      confirmOlder: 'ignorar {n} equipamento mais recente neste telemóvel|ignorar {n} equipamentos mais recentes neste telemóvel',
      confirmLogs: 'juntar {n} registo de serviço (duplicados são ignorados)|juntar {n} registos de serviço (duplicados são ignorados)',
      confirmGo: 'Restaurar',
      title: 'Cópia de segurança',
      intro: 'Os seus equipamentos, fotos e histórico só existem neste telemóvel. Faça uma cópia para nunca perder o seu trabalho — e para mudar de telemóvel. Guarde o ficheiro em local seguro, ou envie-o para si por WhatsApp / e-mail.',
      now: 'Fazer cópia agora', share: 'Enviar cópia para mim', done: 'Cópia guardada',
      lastAt: 'Última cópia: {d}', never: 'Ainda sem cópia.',
      restoreTitle: 'Restaurar', restoreText: 'Restaurar a partir de um ficheiro de cópia (funde com o que já tem).',
      restoreBtn: 'Escolher ficheiro', restored: '{n} máquina restaurada.|{n} máquinas restauradas.',
      reimport: 'Volte a importar o seu {n} manual — fica como o seu próprio PDF.|Volte a importar os seus {n} manuais — ficam como os seus próprios PDF.',
      badFile: 'Esse ficheiro não é uma cópia válida do Taller.',
      tooNew: 'Esta cópia é de uma versão mais recente do Taller.',
      manualsNote: 'Os manuais (os seus PDF) não estão na cópia — reimporte-os após restaurar.',
      remindTitle: 'Proteja os seus dados', remindText: 'Faça cópia dos seus equipamentos e histórico — só existem neste telemóvel.',
    },

    common: {
      confirm: 'Confirmar',
      dismiss: 'Dispensar',
      storageFull: 'O armazenamento do telemóvel está cheio — liberte espaço e tente novamente.',
      cancel: 'Cancelar', save: 'Guardar', delete: 'Eliminar', close: 'Fechar',
      back: 'Voltar', ok: 'OK', share: 'Partilhar', copy: 'Copiar', copied: 'Copiado!',
      loading: 'A carregar…', error: 'Algo correu mal', retry: 'Tentar de novo',
      yes: 'Sim', no: 'Não', optional: 'opcional', search: 'Procurar',
      open: 'Abrir', add: 'Adicionar', done: 'Concluído', stop: 'Parar', edit: 'Editar',
      confirmDelete: 'Eliminar? Não é possível anular.',
    },

    onboarding: {
      more: 'O que faz',
      welcome: 'Bem-vindo ao Taller',
      p1t: 'Todos os manuais no bolso',
      p1s: 'Importe os manuais de serviço PDF que já tem. Ficam no seu telemóvel.',
      p2t: 'Encontre a solução em segundos',
      p2s: 'Procure avarias, códigos de erro ou peças — offline — e salte para a página exata.',
      p3t: 'Grátis para sempre',
      p3s: 'Código aberto. Sem contas, sem anúncios, sem rastreio.',
      chooseLang: 'Idioma',
      start: 'Adicionar o meu primeiro manual',
      tryDemo: 'Experimentar o manual de demo',
      restore: 'Restaurar de uma cópia',
    },

    brand: {
      scanTitle: 'Abra no seu telemóvel',
      scanText: 'Leia com a câmara — o Taller instala-se a partir do navegador e depois funciona totalmente offline.',
      foot: 'Grátis e código aberto (Apache-2.0) · Sem contas · Os seus ficheiros nunca saem do dispositivo',
      shareText: 'Taller — app grátis e de código aberto para técnicos biomédicos: os seus manuais, offline, e a manutenção de equipamentos.',
    },

    library: {
      saving: 'A guardar no telemóvel…',
      importCancelled: 'Importação cancelada — nada foi guardado.',
      storageFull: 'O telemóvel está cheio, por isso o manual não foi guardado. Liberte espaço (fotos, vídeos ou outro manual) e tente de novo.',
      engineOffline: 'A app precisa de internet uma só vez para terminar a instalação. Ligue-se e adicione o manual outra vez — este PDF está bom.',
      title: 'Manuais',
      searchAll: 'Procurar em todos os manuais… (avaria, código de erro)',
      addManual: 'Adicionar manual (PDF)',
      emptyTitle: 'Ainda sem manuais',
      emptyText: 'Adicione os manuais de serviço PDF que já tem no telemóvel. Nunca saem do seu dispositivo.',
      demoBtn: 'Experimentar com um manual de demo',
      importing: 'A importar…',
      readingFile: 'A ler ficheiro…',
      extracting: 'A ler a página {x} de {y}…',
      indexing: 'A criar índice de pesquisa…',
      imported: 'Manual adicionado: {name}',
      importFailed: 'Não foi possível importar este PDF. Pode estar danificado ou protegido.',
      scannedBadge: 'Digitalizado — pesquisa de texto desligada',
      scannedHint: 'Este manual é uma digitalização (fotos de páginas). Pode lê-lo. Use OCR para o tornar pesquisável.',
      makeSearchable: 'Tornar pesquisável (OCR)',
      pages: '{n} página|{n} páginas',
      deleteManual: 'Eliminar manual',
      deleteConfirm: 'Eliminar «{name}» deste dispositivo?',
      storage: 'Armazenamento usado: {used}',
      bigFileWarn: 'Este ficheiro tem {mb} MB. A importação pode ser lenta neste telemóvel. Continuar?',
      betaTitle: 'Isto é uma beta — ajude a decidir o seu futuro',
      betaText: 'Técnicos reais estão a validar se vale a pena construir esta app a sério. A sua opinião decide.',
      betaCta: 'Feedback em 60 segundos',
      installApp: 'Instalar app',
      installed: 'App instalada — já funciona 100 % offline.',
      keepOpen: 'Mantenha a app aberta durante a importação.',
      suggestTitle: 'Experimente uma pesquisa',
      shareApp: 'Partilhar o Taller com um colega',
      linkCopied: 'Ligação copiada — cole onde quiser',
      rename: 'Renomear',
      renamed: 'Renomeado',
      onlyPdf: 'Só é possível importar ficheiros PDF.', demoOffline: 'A demo precisa de internet à primeira vez.',
    },

    find: {
      title: 'Encontrar um manual',
      intro: 'Procure um manual de serviço nestas bibliotecas públicas gratuitas e depois importe o PDF aqui.',
      forDevice: 'O que procura?',
      queryPlaceholder: 'Marca e modelo, ex. Philips SP-100',
      note: 'São bibliotecas independentes de terceiros — a Taller não aloja manuais. Confirme que o manual corresponde ao seu modelo exato. Depois de descarregar, use «Adicionar manual (PDF)» para o importar.',
      offline: 'Está offline — ligue-se à internet para abrir estas bibliotecas.',
      cta: 'Encontrar um manual online',
      open: 'Abrir {name}',
      srcIfixit: '13.000+ manuais de reparação biomédica gratuitos',
      srcFranks: 'Manuais de serviço e guias gratuitos para hospitais com poucos recursos',
      srcMedwrench: 'Biblioteca de equipamentos e fóruns da comunidade',
      srcWebName: 'Pesquisa web',
      srcWeb: 'Procurar um PDF em toda a web',
    },

    search: {
      resultsFor: 'Resultados para «{q}»',
      noResults: 'Sem correspondências nos seus manuais.',
      tips: 'Tente: o código de erro (ex. «E4»), a avaria («não aspira») ou o nome de uma peça.',
      page: 'p. {n}',
    },

    reader: {
      pageOf: '{p} / {n}',
      findInManual: 'Procurar dentro deste manual…',
      copyPageText: 'Copiar texto da página',
      prevPage: 'Página anterior', nextPage: 'Página seguinte', zoomIn: 'Aproximar', zoomOut: 'Afastar',
      copiedPage: 'Texto da página copiado',
      noTextPage: 'Sem texto nesta página (imagem digitalizada).',
      resultCtx: 'Correspondência nesta página:',
    },

    ask: {
      extractBadge: 'Páginas exactas dos seus manuais',
      weakBadge: 'Correspondência fraca',
      weakText: 'Nada nos seus manuais corresponde bem a esta pergunta. As páginas abaixo são as mais próximas, mas podem ser sobre outra coisa — leia-as antes de confiar.',
      insufficientBadge: 'Não está nos seus manuais',
      truncated: 'Esta resposta foi cortada antes do fim. Abra as páginas citadas — podem faltar passos.',
      badCitation: 'Aviso: a página {p} foi citada mas não estava entre as consultadas. Não confie nessa citação.',
      partialPages: 'Só foi lida parte de cada página. Um procedimento pode continuar para além disso — veja a página completa.',
      relevance: 'Relevância',
      conf: { weak: 'baixa', fair: 'média', good: 'alta' },
      title: 'Pergunte aos seus manuais',
      hint: 'Descreva a avaria. A resposta vem APENAS dos manuais que adicionou, citando a página.',
      placeholder: 'ex. O aspirador mostra E3 e para ao fim de alguns segundos',
      allManuals: 'Todos os manuais',
      askBtn: 'Perguntar',
      thinking: 'A responder a partir dos seus manuais…',
      answer: 'Resposta',
      aiBadge: 'IA · ancorada nos seus manuais',
      offlineBadge: 'Offline · trechos exatos dos seus manuais',
      sources: 'Fontes',
      bestPages: 'Páginas que melhor correspondem',
      openPage: 'Abrir p. {n}',
      copyPrompt: 'Copiar prompt para ChatGPT / outra IA',
      promptCopied: 'Prompt copiado. Cole no ChatGPT, Claude, Gemini…',
      aiError: 'Serviço de IA indisponível — mostrando as páginas correspondentes do manual.',
      noMatches: 'Nada encontrado sobre isto nos seus manuais.',
      noMatchesTips: 'Tente outras palavras: o código de erro exato, o nome da peça ou o sintoma. Verifique se o manual certo está importado.',
      safety: 'As respostas vêm apenas dos seus manuais — verifique sempre a página citada antes de agir. Siga os procedimentos de segurança elétrica. Nunca anule seguranças nem alarmes.',
      needManuals: 'Adicione primeiro pelo menos um manual — o assistente só responde a partir dos SEUS manuais.',
      goAdd: 'Adicionar um manual',
      suggestTitle: 'Experimente perguntar',
    },

    logbook: {
      showMore: 'Mostrar mais {n}',
      title: 'Histórico de serviço',
      newEntry: 'Nova entrada',
      logFault: 'Registar avaria',
      setMachine: 'Definir a máquina para:', date: 'Data',
      equipment: 'Equipamento',
      equipmentPh: 'ex. Aspirador — Enfermaria 3',
      noEquip: 'Sem equipamento', otherEquip: 'Outro / fora do registo',
      type: 'Tipo',
      typeRepair: 'Reparação', typePM: 'Preventiva', typeInspection: 'Inspeção',
      problem: 'Problema / trabalho feito',
      problemPh: 'ex. Erro E3 — filtro limpo, tubo substituído',
      status: 'Estado',
      statusFixed: 'Reparado', statusPending: 'Pendente', statusPart: 'Falta peça',
      minutes: 'Minutos gastos',
      addPhoto: 'Adicionar foto',
      saveEntry: 'Guardar entrada',
      saved: 'Entrada guardada',
      empty: 'Sem entradas. Um registo ajuda a justificar o seu trabalho e a planear a manutenção preventiva.',
      emptyEquip: 'Ainda sem histórico para esta máquina.',
      export: 'Exportar CSV',
      exported: 'CSV exportado',
      entries: '{n} entrada|{n} entradas',
    },

    feedback: {
      title: 'Feedback em 60 segundos',
      intro: 'Esta beta existe para responder a uma pergunta: o Taller ajudaria técnicos reais? A sua resposta honesta — incluindo «não» — decide se vale a pena construí-lo a sério.',
      q1: 'Encontrar o manual ou a página certa — com que frequência é um problema no seu trabalho?',
      q1a: 'Todas as semanas', q1b: 'Às vezes', q1c: 'Raramente',
      q2: 'Internet na sua oficina:',
      q2a: 'Nenhuma / muito má', q2b: 'Vai e vem', q2c: 'Estável e acessível',
      q3: 'Já usa o ChatGPT ou outra IA com os seus PDF para reparações?',
      q3a: 'Sim, funciona bem', q3b: 'Experimentei — não ajudou muito', q3c: 'Nunca experimentei',
      q4: 'Um registo de avarias com menos de 1 minuto por entrada — usá-lo-ia?',
      q4a: 'Sim', q4b: 'Talvez', q4c: 'Não',
      q5: 'Quantos dos seus manuais são fotocópias digitalizadas?',
      q5a: 'A maioria', q5b: 'Alguns', q5c: 'Quase nenhum',
      comments: 'Esta app ajudá-lo-ia no trabalho real? O que falta?',
      commentsPh: 'Seja direto — respostas honestas valem mais que simpáticas.',
      country: 'País + função',
      countryPh: 'ex. Moçambique, técnico biomédico hospitalar',
      includeStats: 'Incluir as minhas estatísticas de uso (manuais adicionados, pesquisas — nada mais)',
      sendEmail: 'Enviar por e-mail',
      sendShare: 'Enviar por WhatsApp / outra app',
      copyAll: 'Copiar as minhas respostas (colar no fórum / WhatsApp)',
      thanks: 'Obrigado! A sua opinião decide o que acontece a seguir.',
      answerFirst: 'Responda primeiro a pelo menos uma pergunta.',
    },

    ocr: {
      needInternet: 'O OCR precisa de internet uma só vez para descarregar o motor (~7 MB). Ligue-se à internet e tente de novo.',
      engineReady: 'O motor de OCR já está no telemóvel — funciona offline.',
      savedAsYouGo: 'As páginas são guardadas à medida que são lidas — pode parar quando quiser e continuar mais tarde.',
      storageFull: 'O telemóvel está cheio. As páginas já lidas estão guardadas; liberte espaço para terminar.',
      title: 'Tornar o manual pesquisável',
      intro: 'Este manual está digitalizado (fotos de páginas). O OCR lê o texto para permitir a pesquisa. Tudo acontece no seu telemóvel: cerca de 10 a 40 segundos por página. Mantenha a app aberta, de preferência ligada à corrente.',
      firstTime: 'A primeira vez precisa de internet uma só vez (motor de OCR, ~7 MB). Depois funciona offline.',
      lang: 'Idioma do manual',
      start: 'Iniciar OCR',
      progress: 'A ler a página {x} de {y}…',
      done: 'Concluído — {n} páginas já são pesquisáveis.',
      stopped: 'Parado. As {n} páginas processadas já são pesquisáveis.',
      failed: 'O OCR não conseguiu funcionar neste dispositivo.',
    },

    more: {
      offlinePartial: 'Parcialmente pronto para uso offline. Fique ligado mais um momento para terminar a transferência.',
      offlineFailed: 'Não foi possível concluir a instalação para uso offline. Reabra a app com ligação.',
      title: 'Mais',
      language: 'Idioma',
      theme: 'Tema', themeAuto: 'Auto', themeLight: 'Claro', themeDark: 'Escuro',
      feedbackCta: 'Dar feedback (60 s)',
      aiTitle: 'Assistente IA (online)',
      aiOn: 'Ligado — respostas ancoradas quando tiver internet.',
      aiOff: 'Sem configurar. A app funciona offline: pesquisa + trechos exatos + copiar prompt. O projeto pode ativar um servidor de IA gratuito opcional.',
      aiUrl: 'URL do servidor de IA',
      storageTitle: 'Armazenamento',
      persistOn: 'Armazenamento protegido: os seus manuais não serão apagados automaticamente.',
      persistOff: 'Armazenamento ainda não protegido — instale a app para o proteger.',
      aboutTitle: 'Sobre o Taller',
      aboutText: 'Grátis e código aberto, para sempre. Sem anúncios, sem contas, sem rastreio. Os seus manuais e registos nunca saem do telemóvel (se ativar a IA online, só são enviados os trechos necessários para responder, e nada é guardado). Feito para técnicos biomédicos de todo o mundo.',
      disclaimer: 'O Taller é uma ferramenta de informação para profissionais. Não substitui a documentação do fabricante, a formação nem a regulamentação local. Verifique sempre as páginas citadas e siga os procedimentos de segurança.',
      source: 'Código-fonte',
      license: 'Licença: Apache-2.0',
      reset: 'Apagar TODOS os dados',
      resetConfirm: 'Apagar todos os manuais, registos e definições deste dispositivo?',
      version: 'Versão',
      openInChrome: 'Para instalar e usar offline, abra esta página no Chrome (menu ⋮ → Abrir no Chrome).',
      updateReady: 'Atualização pronta — feche e reabra a app.',
      reload: 'Recarregar',
      offlineReady: 'Pronto — o Taller já funciona sem internet.',
    },
  },
};
